In [ ]:
import cv2
import numpy as np

input_path = r'C:\Users\verci\Documents\code\Physics157\PHYSICS192 CODE\Set B\Sig_adder\signatures\dumas.png'
output_path = r'C:\Users\verci\Documents\code\Physics157\PHYSICS192 CODE\Set B\Sig_adder\signatures\dumas_bgn.png'
mask = np.array([200, 200, 200])
img = cv2.imread(input_path)
img_rgba = cv2.cvtColor(img, cv2.COLOR_BGR2BGRA)
to_transparent = np.all(img[:, :, :3] > mask, axis=2)
img_rgba[to_transparent, 3] = 0
cv2.imwrite(output_path, img_rgba)
print("Done.")


[[[254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]
  ...
  [254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]]

 [[254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]
  ...
  [254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]]

 [[254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]
  ...
  [254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]]

 ...

 [[254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]
  ...
  [254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]]

 [[254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]
  ...
  [254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]]

 [[254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]
  ...
  [254 254 254 255]
  [254 254 254 255]
  [254 254 254 255]]]
Done.
